name: Download image

on:
  pull_request:
    branches:
      - main

jobs:
  load_image:
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    environment: downloading

    env:
      MINIO_URL: ${{ vars.MINIO_URL }}
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}
      FILE_PATH: ${{ vars.FILE_PATH }}
      LOCAL_PATH: ${{ vars.LOCAL_PATH }}
      ACCESS_KEY: ${{ vars.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      HASH_STRING: ${{ vars.HASH_STRING }}

    steps:

      - uses: actions/checkout@v4

      - name: Install MinIO client
        run: |
          apt-get update
          apt-get install curl -y
          curl https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc
          chmod +x /usr/local/bin/mc

      - name: Configure MinIO
        run: |
          mc alias set minio $MINIO_URL $ACCESS_KEY $SECRET_KEY

      - name: Download image
        run: |
          mc cp minio/$BUCKET_NAME/$FILE_PATH $LOCAL_PATH

      - name: Check md5
        run: |
          echo "$HASH_STRING $LOCAL_PATH" | md5sum -c